### ISSUE TITLE
Security with IAM support

### ISSUE THREAD

**Issue by Lokicity** [uswitch/kiam#241]
Hi, I have a question with the security aspect . For example, I have 1 pod running on my cluster and the pod needs access to another AWS account 1. In order to assume the role from AWS account, I put the annotation on pod with rolename in AWS account 1. With KIAM, I am able to access AWS account 1 now. 

If some malicious users get my API server credential, he can potential create a new pod in a new namespace. And with the proper annotation, he will be able to access the AWS account 1 using the role that my other pod was using. 

With the multiple IAM support model, if I have N pods accessing N AWS accounts, if a malicious users who manage to get my APIserver credential, he could ended up get access to all N AWS accounts. 

Is there a solution on this issue? Is there something we can do with external ID to harden the security here? If we only put externalID as a pod annotation, the malicious user can still get access to the AWS account because he can just run a "describe pod".

Thanks

**Comment by Joseph-Irving** [comment]
If a user has a managed to get into your cluster and has full admin capabilities to the extent that they can create namespaces, pods and can has knowledge of the aws roles they want to assume then I don't think there's much you can do to stop them.

I don't think this problem is specific to Kiam, if you were using instance roles to access other aws accounts resources then you would have the same problem but the attacker would only need to compromise a node/pod. Alternatively if you're using static secrets with credentials then if the attacker has api access they can retrieve them.

I would focus on making sure your kube api is secure and following best practices to prevent the scenario of an attacker getting root access.
