### ISSUE TITLE
Changelog for helm/stable/kiam

### ISSUE THREAD

**Issue by tretos53** [uswitch/kiam#286]
As I'm using helm/kiam and upgrading from 2.1.0 it would be good to know what changed.

Is there a changelog for helm/stable/kiam? I generated one from Commits but it only include 2.5.1. 

Is there anything prior to this?

Very short generated CHANGELOG.md that could be a good start?

```
##   2.5.1

Updated READMEs and include uSwitch logo in chart
commit: 9c2bc7a 

##   2.5.1

Update maintainer
commit: 39d5ef5 

##   2.5.1

Add helm chart files and ci step
commit: cc349ca 
```

**Comment by rhysemmas** [comment]
The Kiam Helm chart versions prior to (and including) 2.5.1 were maintained by the Helm community at:
https://github.com/helm/charts/tree/master/stable/kiam
These versions were included in Helm's `stable/kiam` repository. We have started hosting the Helm chart ourselves as of chart version 2.5.1, hence you won't see any commits in this repo from before this.

We have decided to host the Kiam chart ourselves as we hope this will make it easier for the community to contribute to the chart and raise any changes and issues which can be more quickly addressed. Our versions of the chart can be installed by adding the `uswitch/kiam` repository to the helm cli:

```console
helm repo add uswitch https://uswitch.github.io/kiam-helm-charts/charts/
helm repo update

helm install uswitch/kiam
```

I like the idea of having a changelog in this repo so there is better clarity on what's changed between chart versions, but this will likely just include details of changes made to this repo going forwards.

Currently, there are no changes in functionality between `uswitch/kiam` and Helm's `stable/kiam` version 2.5.1, but, it does look like a fair amount has been added since version 2.1.0 of the chart (including updating to later releases of Kiam). Therefore, I would recommend checking out the changes in the Helm repo mentioned above if you are planning on upgrading.
