### ISSUE TITLE
Create docs for upgrading to v4

### ISSUE THREAD

**Issue by pingles** [uswitch/kiam#436]
There's been a number of breaking changes #435 #431 introduced recently.

Before releasing we'll need something in the upgrading doc and release notes to help people understand the changes. In particular, changes to when regexes are applied will affect running workloads.

**Comment by leosunmo** [comment]
From https://github.com/uswitch/kiam/pull/435
> @leosunmo what do you think? Could you prep some examples of how the namespace regex behaved before, and now, and what the implications are please?

Looking back at my [original issue](https://github.com/uswitch/kiam/issues/326) I can't think of a scenario where the "new" process would result in _more_ permissive behaviour, but potentially where it is _less_ permissive after the ARN resolver is added.

First, to recap and to get something started for the 4.0 Upgrade guide.
Using the following scenario from the original ticket:

```
# namespace
annotations:
  iam.amazonaws.com/permitted: .*workloads/.*
```
```
# Kiam Server
--role-base-arn=arn:aws:iam::1234567890:role/workloads/
```

```
# pod
annotations:
  iam.amazonaws.com/role: my-amazing-role
```
#### Old behaviour, where role ARN is _NOT_ resolved before rules are evaluated
Fails, since `my-amazing-role` != `.*workloads/.*`:

`failed assuming role "my-amazing-role": namespace policy expression '.*workloads/.*' forbids role 'my-amazing-role'`


#### _New_ behaviour, where the role is fully expanded/resolved before rules are evaluated.
Passes, since `role` = `role-base-arn` + `pod annotation`:

`arn:aws:iam::1234567890:role/workloads/my-amazing-role` == `.*workloads/.*`
Success!

---

A scenario that would pass evaluation using the old evaluation:
```
# namespace
annotations:
  iam.amazonaws.com/permitted: ^red-role$
```
```
# Kiam Server
--role-base-arn=arn:aws:iam::1234567890:role/workloads/
```

```
# pod
annotations:
  iam.amazonaws.com/role: red-role
```

Not very realistic, or likely to actually affect anyone, but this would currently pass and fail using the new evaluation implementation.

**Comment by leosunmo** [comment]
Something that will have more impact on behaviour and backwards compatibility is https://github.com/uswitch/kiam/issues/328 / https://github.com/uswitch/kiam/pull/329

**Comment by stefansedich** [comment]
https://github.com/uswitch/kiam/pull/437 is also a breaking change.
