### ISSUE TITLE
'error warming credentials' but AWS CLI works

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#5]
I've seen messages such as this one:
~~~~
time="2017-06-02T12:21:36Z" level=error msg="error warming credentials: AccessDenied: Not authorized to perform sts:AssumeRole\n\tstatus code: 403, request id: 059aab77-478e-11e7-a540-2938881f4c35" generation.metadata=0 pod.iam.role="arn:aws:iam::XXXXXXXX:role/YYYYYY" pod.name=.... pod.namespace=.... pod.status.ip=10.2.28.39 pod.status.phase=Running resource.version=26173143 
~~~~

I tried a simple `aws sts assume-role --role-session test --role-arn arn:aws:iam::XXXXXXXX:role/YYYYYY` on the node and in the kiam pod, and in both cases got credentials. 

FWIW: I'm in the eu-west-1 region -- this might be due to an assumption somewhere about the region, but that's just a guess.

**Comment by pingles** [comment]
In the log data you should have `pod.iam.role` and `pod.name`- could you just check whether you see it for a few roles or across all roles. Not sure what the problem could be but that may help narrow it down.

We also run in `eu-west-1` so don't think it'd be a region issue.

**Comment by ankon** [comment]
Yes, the ARNs were definitely the same, checked my logs as well to be sure.

**Comment by pingles** [comment]
@ankon not sure if you are still using/could confirm whether this is related to https://github.com/uswitch/kiam/issues/7 - that the error was because `AssumeRole` was being called by a node that wasn't permitted to make the call?

I'm going to close this for now- if it happens with v2 then we can definitely re-open another issue.
